#!/bin/bash

################################################################################
#
# Prepares commit message so that it contains the issue number extracted from
#   the branch name.
# Issue numbers are matched against the [a-zA-Z]+-[0-9]+ regex
#
################################################################################

DEFAULT_PATTERN='[a-zA-Z]+-[0-9]+'

FIRST_LINE=$(head -n1 $1)

if [ -z "$FIRST_LINE"  ] ;then #Check that this is not an amend by checking that the first line is empty

    BRANCH_NAME="$(git symbolic-ref HEAD 2>/dev/null)" ||
    BRANCH_NAME="(unnamed branch)"     # detached HEAD

    BRANCH_NAME=${BRANCH_NAME##refs/heads/}
    
    ISSUE_PATTERN_CONFIG="$(git config issue.pattern)"

    ISSUE_PATERN=${ISSUE_PATTERN_CONFIG:-$DEFAULT_PATTERN}

    ISSUE_NUMBER=$(echo $BRANCH_NAME | awk --posix -F ' ' 'match($0, /'"$ISSUE_PATERN"'/) { print substr($0, RSTART, RLENGTH) }' )
    
    sed -i "1s/^/\n\n${ISSUE_NUMBER}/" $1
fi
